ALTER SESSION SET NLS_TERRITORY='Cameroon';
ALTER SESSION SET NLS_LANGUAGE='French';
SET LINESIZE 300
ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT='HH24/MM/SS';
spool install.log
@@OBJECTS/run
@@DATA/run

set linesize 300
-- @@PLSQL/start

spool off
